In [1]:
import pandas as pd
from src.recovery_model import RecoveryModel

pd.set_option("multi_sparse", False)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
# Select a folder for the data to be used
folder = "test_2"  # choose between: test_1  test_2  Toy_WEEE_v2
layer_0 = "flow"
layer_1 = "product"
layer_2 = "component"
layer_3 = "material"
layer_4 = "element"

In [3]:
# This section insures that the structure of the excel files is consistent
# ! PLEASE IGNORE FOR NOW

layer_names = (layer_0, layer_1, layer_2, layer_3, layer_4)
all_symbols = {layer_1: "P*", layer_2: "C*", layer_3: "M*", layer_4: "E*"}

metadata = {
    "path": f"data/{folder}/",
    "filename": "metadata.csv",
}
composition = {
    "path": f"data/{folder}/",
    "filename": "composition.csv",
    "mapper": {
        "Stock/Flow ID": layer_0,
        "Layer 1": layer_1,
        "Layer 2": layer_2,
        "Layer 3": layer_3,
        "Layer 4": layer_4,
        "Value": "data",
        "parameterCode": "parameterCode",
        "Year": "year",  # not considered at this stage
        "Scenario": "scenario",  # not considered at this stage
        "Location": "region",  # not considered at this stage
        "UoM": "unit",  # not considered at this stage
    },
    # only values accepted for the parameterCode column
    # ! do not change
    "parameterCode": {
        layer_2: "c-p",
        layer_3: "m-c",
        layer_4: "e-m",
    },
}

inputs = {
    "path": f"data/{folder}/",
    "filename": "inputs.csv",
    "mapper": {
        "Stock/Flow ID": layer_0,
        "Substance_main_parent": layer_1,
        "Value": "data",
        "Unit": "unit",
        "Year": "year",  # not considered at this stage
    },
}

tcs = {
    "path": f"data/{folder}/",
    "filename": "TCs.csv",
    "mapper": {
        # inflows / outflows
        "input_flow": "inflows",
        "output_flow": "outflows",
        # levels
        "input_layer": "input_layer1_level",
        "input_sub_layer": "input_layer2_level",
        "output_layer": "output_layer1_level",
        # keys
        "input_layer_key": "input_layer1_key",
        "input_sub_layer_key": "input_layer2_key",
        "output_target_key": "output_layer1_key",
        # other columns
        "value": "data",
        "process": "process",
        "Year": "year",  # not considered at this stage
    },
    "all_symbols": {
        layer_1: "P*",
        layer_2: "C*",
        layer_3: "M*",
        layer_4: "E*",
    },
}

---

# Recovery model

In [4]:
model = RecoveryModel(
    name=folder,
    metadata=metadata,
    composition=composition,
    inputs=inputs,
    tcs=tcs,
    layer_names=layer_names,
    save_intermediary_steps=False,
    save_duplicates=False,
)

---

# Metadata

In [5]:
model.dims

(8, 3, 4, 3, 3)

In [6]:
model.size

864

In [7]:
model.flows_eqs

         F1  F2  F3  F4  F5  F6  F7  F8
process
T1        1  -1  -1   0   0   1   0   0
T2        0   1   0  -1  -1   0   0   0
T3        0   0   0   0   1   0   1  -1
T4        0   0   1   1   0  -1  -1   0

---

# Model equation

$$(I - A^T)x = y$$

<img src="./doc/img/model_equation.png" alt="model_equation" width="350" />

In [8]:
model.lneqs  # the A matrix (it will be properly renamed later)

<864x864 sparse matrix of type '<class 'numpy.float64'>'
	with 441 stored elements in Compressed Sparse Row format>

In [9]:
model.y

<864x1 sparse array of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Column format>

---

# Solver

In [10]:
model.solve(aggregate=False, pivot=False).fillna("")

    flow product component material element    data
0     F1      P1                            1000.00
1     F1      P1        C1                   250.00
2     F1      P1        C1       M1          130.00
3     F1      P1        C1       M1      E1   91.00
4     F1      P1        C1       M1      E2   39.00
..   ...     ...       ...      ...     ...     ...
175   F8      P1        C3       M2      E2    0.40
176   F8      P2        C1       M1      E1    0.23
177   F8      P2        C1       M2      E2    0.09
178   F8      P2        C2       M1      E1    0.28
179   F8      P2        C2       M2      E2    0.07

[180 rows x 6 columns]

In [11]:
model.solve(aggregate=False, pivot=True).fillna("")

flow,product,component,material,element,F1,F2,F3,F4,F5,F6,F7,F8
0,P1,,,,1000.00,,,,,,,
1,P1,C1,,,250.00,62.50,,,,,,
2,P1,C1,M1,,130.00,32.50,,,12.68,,,
3,P1,C1,M1,E1,91.00,22.75,,,8.87,,,1.60
4,P1,C1,M1,E2,39.00,9.75,,,3.80,,,
5,P1,C1,M2,,120.00,30.00,,,9.60,,,
6,P1,C1,M2,E1,117.60,29.40,,,9.41,,,
7,P1,C1,M2,E2,2.40,0.60,,,0.19,,,0.01
8,P1,C2,,,590.00,27.76,26.86,5.55,,11.24,,
9,P1,C2,M1,,389.40,18.32,17.73,3.66,1.83,7.42,2.08,
10,P1,C2,M1,E1,109.03,5.13,4.96,1.03,0.51,2.08,0.58,0.17
11,P1,C2,M1,E2,280.37,13.19,12.76,2.64,1.32,5.34,1.50,
12,P1,C2,M2,,200.60,9.44,9.13,1.89,4.72,3.82,2.04,
13,P1,C2,M2,E1,16.05,0.76,0.73,0.15,0.38,0.31,0.16,
14,P1,C2,M2,E2,184.55,8.68,8.40,1.74,4.34,3.52,1.88,0.62
15,P1,C3,,,160.00,,13.04,,,1.83,,
16,P1,C3,M1,,78.40,,6.39,,,0.89,0.83,
17,P1,C3,M1,E1,25.09,,2.04,,,0.29,0.27,0.04
18,P1,C3,M1,E2,53.31,,4.34,,,0.61,0.56,
19,P1,C3,M2,,81.60,,6.65,,,0.93,2.59,
20,P1,C3,M2,E1,14.69,,1.20,,,0.17,0.47,
21,P1,C3,M2,E2,66.91,,5.45,,,0.76,2.13,0.40
22,P2,,,,700.00,,,,,,,
23,P2,C1,,,301.00,24.08,,,,,,
24,P2,C1,M1,,156.52,12.52,,,4.88,,,
25,P2,C1,M1,E1,40.70,3.26,,,1.27,,,0.23
26,P2,C1,M1,E2,115.82,9.27,,,3.61,,,
27,P2,C1,M2,,144.48,11.56,,,3.70,,,
28,P2,C1,M2,E1,88.13,7.05,,,2.26,,,
29,P2,C1,M2,E2,56.35,4.51,,,1.44,,,0.09
30,P2,C2,,,49.00,23.81,12.54,4.76,,6.07,,
31,P2,C2,M1,,43.61,21.19,11.16,4.24,2.12,5.41,1.66,
32,P2,C2,M1,E1,20.06,9.75,5.13,1.95,0.97,2.49,0.76,0.28
33,P2,C2,M1,E2,23.55,11.44,6.03,2.29,1.14,2.92,0.89,
34,P2,C2,M2,,5.39,2.62,1.38,0.52,1.31,0.67,0.36,
35,P2,C2,M2,E1,2.70,1.31,0.69,0.26,0.65,0.33,0.18,
36,P2,C2,M2,E2,2.70,1.31,0.69,0.26,0.65,0.33,0.18,0.07
37,P2,C3,,,350.00,,,,,,,
38,P2,C3,M1,,122.50,,,,,,,
39,P2,C3,M1,E1,85.75,,,,,,,
40,P2,C3,M1,E2,36.75,,,,,,,
41,P2,C3,M2,,227.50,,,,,,,
42,P2,C3,M2,E1,65.97,,,,,,,
43,P2,C3,M2,E2,161.53,,,,,,,

---

# Mass balance

In [12]:
# folder = "Toy_WEEE_v2"
mass_balance = pd.read_csv(f"consolidation/{folder}_solution_mass_balance.csv", index_col=0)
mass_balance.fillna("")

,product,component,material,element,process,F1,F2,F3,F4,F5,F6,F7,F8,mass_balance
0,P1,,,,T1,1000.00,,,,,,,,1000.00
1,P1,C1,,,T1,250.00,-62.50,,,,,,,187.50
2,P1,C1,M1,,T1,130.00,-32.50,,,0.00,,,,97.50
3,P1,C1,M1,E1,T1,91.00,-22.75,,,0.00,,,0.00,68.25
4,P1,C1,M1,E2,T1,39.00,-9.75,,,0.00,,,,29.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,P2,C2,M1,E1,T3,0.00,0.00,0.00,0.00,0.97,0.00,0.76,-0.28,1.45
119,P2,C2,M1,E2,T3,0.00,0.00,0.00,0.00,1.14,0.00,0.89,,2.04
120,P2,C2,M2,,T3,0.00,0.00,0.00,0.00,1.31,0.00,0.36,,1.67
121,P2,C2,M2,E1,T3,0.00,0.00,0.00,0.00,0.65,0.00,0.18,,0.83
122,P2,C2,M2,E2,T3,0.00,0.00,0.00,0.00,0.65,0.00,0.18,-0.07,0.76

In [13]:
impossible_rows = mass_balance["mass_balance"] < 0
mass_balance[impossible_rows].fillna("")

Empty DataFrame
Columns: [product, component, material, element, process, F1, F2, F3, F4, F5, F6, F7, F8, mass_balance]
Index: []